/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author jhon
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        Entrar = new javax.swing.JMenu();
        btn_login = new javax.swing.JMenuItem();
        Proveedores = new javax.swing.JMenu();
        btn_proveedores = new javax.swing.JMenuItem();
        Aves = new javax.swing.JMenu();
        btn_CRUDAves = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        btn_CRUDRejas = new javax.swing.JMenuItem();
        Carros = new javax.swing.JMenu();
        btn_CRUDChofer = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        btn_CRUDCarros = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        btn_CRUDRutas = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenu();
        btn_CRUDClientes = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        btn_Credito = new javax.swing.JMenuItem();
        Ventas = new javax.swing.JMenu();
        btn_Ventas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        btn_facturar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btn_impresiones = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        btn_insumos = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        btn_movimientoFactura = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        reporetInsumos = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        btn_estadoFactura = new javax.swing.JMenuItem();
        Configuraciones = new javax.swing.JMenu();
        btn_CRUDUsuarios = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        btn_ConfigBascula = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenu();
        btn_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedor.setBackground(java.awt.SystemColor.controlLtHighlight);

        Entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio.png"))); // NOI18N
        Entrar.setMnemonic('f');
        Entrar.setText("<html>  <style type=\"text/css\">  .estilo1{font-family:Dialog;font-weight:bold; font-size:12px;color:rgb(0, 0, 0);}  .estilo2{font-family:Dialog;font-weight:bold; font-size:10px;color:rgb(153, 153, 153);}  </style>  <span class=\"estilo1\"><u>Entrar</u></span><br/>   </html>  ");
        Entrar.setToolTipText("");
        Entrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Entrar.setInheritsPopupMenu(true);

        btn_login.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        btn_login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/login.png"))); // NOI18N
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        Entrar.add(btn_login);

        menuBar.add(Entrar);

        Proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/company.png"))); // NOI18N
        Proveedores.setText("<html>  <style type=\"text/css\">  .estilo1{font-family:Dialog;font-weight:bold; font-size:12px;color:rgb(0, 0, 0);}  .estilo2{font-family:Dialog;font-weight:bold; font-size:10px;color:rgb(153, 153, 153);}  </style>  <span class=\"estilo1\"><u>Proveedores</u></span><br/>   </html>  ");
        Proveedores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btn_proveedores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        btn_proveedores.setText("Registro Proveedores");
        btn_proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proveedoresActionPerformed(evt);
            }
        });
        Proveedores.add(btn_proveedores);

        menuBar.add(Proveedores);

        Aves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pollo.png"))); // NOI18N
        Aves.setMnemonic('h');
        Aves.setText("<html>  <style type=\"text/css\">  .estilo1{font-family:Dialog;font-weight:bold; font-size:12px;color:rgb(0, 0, 0);}  .estilo2{font-family:Dialog;font-weight:bold; font-size:10px;color:rgb(153, 153, 153);}  </style>  <span class=\"estilo1\"><u>Aves</u></span><br/>   </html>  ");
        Aves.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btn_CRUDAves.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_CRUDAves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/entrada.png"))); // NOI18N
        btn_CRUDAves.setText("Entradas");
        btn_CRUDAves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CRUDAvesActionPerformed(evt);
            }
        });
        Aves.add(btn_CRUDAves);
        Aves.add(jSeparator7);

        btn_CRUDRejas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/almacen.png"))); // NOI18N
        btn_CRUDRejas.setText("Agregar, Modificar Rejas");
        Aves.add(btn_CRUDRejas);

        menuBar.add(Aves);

        Carros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/prove.png"))); // NOI18N
        Carros.setText("<html>  <style type=\"text/css\">  .estilo1{font-family:Dialog;font-weight:bold; font-size:12px;color:rgb(0, 0, 0);}  .estilo2{font-family:Dialog;font-weight:bold; font-size:10px;color:rgb(153, 153, 153);}  </style>  <span class=\"estilo1\"><u>Carros</u></span><br/>   </html>  ");
        Carros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btn_CRUDChofer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/conductor.png"))); // NOI18N
        btn_CRUDChofer.setText("Agregar, Modificar Chofer");
        Carros.add(btn_CRUDChofer);
        Carros.add(jSeparator5);

        btn_CRUDCarros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/coche.png"))); // NOI18N
        btn_CRUDCarros.setText("Agregar, Modificar Carros");
        Carros.add(btn_CRUDCarros);
        Carros.add(jSeparator6);

        btn_CRUDRutas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mapa.png"))); // NOI18N
        btn_CRUDRutas.setText("Agregar, Modificar Rutas");
        Carros.add(btn_CRUDRutas);

        menuBar.add(Carros);

        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N
        Clientes.setText("<html>  <style type=\"text/css\">  .estilo1{font-family:Dialog;font-weight:bold; font-size:12px;color:rgb(0, 0, 0);}  .estilo2{font-family:Dialog;font-weight:bold; font-size:10px;color:rgb(153, 153, 153);}  </style>  <span class=\"estilo1\"><u>Clientes</u></span><br/>   </html>  ");
        Clientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btn_CRUDClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregarcliente.png"))); // NOI18N
        btn_CRUDClientes.setText("Agregar, Modificar, Eliminar");
        Clientes.add(btn_CRUDClientes);
        Clientes.add(jSeparator10);

        btn_Credito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/money.png"))); // NOI18N
        btn_Credito.setText("Creditos");
        Clientes.add(btn_Credito);

        menuBar.add(Clientes);

        Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cash.png"))); // NOI18N
        Ventas.setText("<html>  <style type=\"text/css\">  .estilo1{font-family:Dialog;font-weight:bold; font-size:12px;color:rgb(0, 0, 0);}  .estilo2{font-family:Dialog;font-weight:bold; font-size:10px;color:rgb(153, 153, 153);}  </style>  <span class=\"estilo1\"><u>Venta</u></span><br/>   </html>  ");
        Ventas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btn_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bolsa.png"))); // NOI18N
        btn_Ventas.setText("Realizar venta");
        Ventas.add(btn_Ventas);
        Ventas.add(jSeparator2);

        btn_facturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/portapapeles.png"))); // NOI18N
        btn_facturar.setText("Registro de Ventas");
        Ventas.add(btn_facturar);
        Ventas.add(jSeparator1);

        btn_impresiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/impresora.png"))); // NOI18N
        btn_impresiones.setText("Impresión de Rutas");
        Ventas.add(btn_impresiones);
        Ventas.add(jSeparator3);

        btn_insumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eyesj-doc.png"))); // NOI18N
        btn_insumos.setText("Insumos");
        Ventas.add(btn_insumos);

        menuBar.add(Ventas);

        Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte.png"))); // NOI18N
        Reportes.setText("<html>  <style type=\"text/css\">  .estilo1{font-family:Dialog;font-weight:bold; font-size:12px;color:rgb(0, 0, 0);}  .estilo2{font-family:Dialog;font-weight:bold; font-size:10px;color:rgb(153, 153, 153);}  </style>  <span class=\"estilo1\"><u>Reportes</u></span><br/>   </html>  ");
        Reportes.setToolTipText("");
        Reportes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btn_movimientoFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporteFactura.png"))); // NOI18N
        btn_movimientoFactura.setText("Movimiento de Factura Pollos");
        btn_movimientoFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_movimientoFacturaActionPerformed(evt);
            }
        });
        Reportes.add(btn_movimientoFactura);
        Reportes.add(jSeparator4);

        reporetInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporteConsumibles.png"))); // NOI18N
        reporetInsumos.setText("Reporte de Insumos o Rutas");
        reporetInsumos.setActionCommand("<html>  <style type=\"text/css\">  .estilo1{font-family:Dialog;font-weight:bold; font-size:9px;color:rgb(0, 0, 0);}  .estilo2{font-family:Dialog;font-weight:bold; font-size:7px;color:rgb(153, 153, 153);}  </style>  <span class=\"estilo1\"><u>Detalles de Insumos</u></span><br/>   </html>  ");
        reporetInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporetInsumosActionPerformed(evt);
            }
        });
        Reportes.add(reporetInsumos);
        Reportes.add(jSeparator9);

        btn_estadoFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/facturadetail.png"))); // NOI18N
        btn_estadoFactura.setText("Estados Factura");
        Reportes.add(btn_estadoFactura);

        menuBar.add(Reportes);

        Configuraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion.png"))); // NOI18N
        Configuraciones.setText("<html>  <style type=\"text/css\">  .estilo1{font-family:Dialog;font-weight:bold; font-size:12px;color:rgb(0, 0, 0);}  .estilo2{font-family:Dialog;font-weight:bold; font-size:10px;color:rgb(153, 153, 153);}  </style>  <span class=\"estilo1\"><u>Configuración</u></span><br/>   </html>  ");
        Configuraciones.setToolTipText("");
        Configuraciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btn_CRUDUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleado.png"))); // NOI18N
        btn_CRUDUsuarios.setText("Agregar, Modificar Empleados");
        btn_CRUDUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CRUDUsuariosActionPerformed(evt);
            }
        });
        Configuraciones.add(btn_CRUDUsuarios);
        Configuraciones.add(jSeparator8);

        btn_ConfigBascula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bascula.png"))); // NOI18N
        btn_ConfigBascula.setText("Configuracion Bascula");
        Configuraciones.add(btn_ConfigBascula);

        menuBar.add(Configuraciones);

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        Salir.setText("<html>  <style type=\"text/css\">  .estilo1{font-family:Dialog;font-weight:bold; font-size:12px;color:rgb(0, 0, 0);}  .estilo2{font-family:Dialog;font-weight:bold; font-size:10px;color:rgb(153, 153, 153);}  </style>  <span class=\"estilo1\"><u>Salir</u></span><br/>   </html>  ");
        Salir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        btn_salir.setText("Salir de la aplicación");
        Salir.add(btn_salir);

        menuBar.add(Salir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 1311, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proveedoresActionPerformed
        
    }//GEN-LAST:event_btn_proveedoresActionPerformed

    private void btn_CRUDAvesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CRUDAvesActionPerformed

    
    }//GEN-LAST:event_btn_CRUDAvesActionPerformed

    private void btn_CRUDUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CRUDUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CRUDUsuariosActionPerformed

    private void btn_movimientoFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_movimientoFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_movimientoFacturaActionPerformed

    private void reporetInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporetInsumosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reporetInsumosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Aves;
    public javax.swing.JMenu Carros;
    public javax.swing.JMenu Clientes;
    public javax.swing.JMenu Configuraciones;
    public javax.swing.JMenu Entrar;
    public javax.swing.JMenu Proveedores;
    public javax.swing.JMenu Reportes;
    public javax.swing.JMenu Salir;
    public javax.swing.JMenu Ventas;
    public javax.swing.JMenuItem btn_CRUDAves;
    public javax.swing.JMenuItem btn_CRUDCarros;
    public javax.swing.JMenuItem btn_CRUDChofer;
    public javax.swing.JMenuItem btn_CRUDClientes;
    public javax.swing.JMenuItem btn_CRUDRejas;
    public javax.swing.JMenuItem btn_CRUDRutas;
    public javax.swing.JMenuItem btn_CRUDUsuarios;
    public javax.swing.JMenuItem btn_ConfigBascula;
    public javax.swing.JMenuItem btn_Credito;
    public javax.swing.JMenuItem btn_Ventas;
    public javax.swing.JMenuItem btn_estadoFactura;
    public javax.swing.JMenuItem btn_facturar;
    public javax.swing.JMenuItem btn_impresiones;
    public javax.swing.JMenuItem btn_insumos;
    public javax.swing.JMenuItem btn_login;
    public javax.swing.JMenuItem btn_movimientoFactura;
    public javax.swing.JMenuItem btn_proveedores;
    public javax.swing.JMenuItem btn_salir;
    public javax.swing.JDesktopPane contenedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuBar menuBar;
    public javax.swing.JMenuItem reporetInsumos;
    // End of variables declaration//GEN-END:variables
}
